language: node_js
sudo: false
node_js:
- stable
addons:
  firefox: '42.0'
cache:
  directories:
  - node_modules
before_script:
- npm install web-component-tester bower polylint
- bower install
- polylint
- export PATH=$PWD/node_modules/.bin:$PATH
script:
- xvfb-run wct
- "./gpages_build.sh Collaborne info@collaborne.com"
env:
  secure: saZ6XSATpvUKRkqgkrKFIIV0mh19XAyerqtFdp08oZppx1iid/eXFLDg+yZHj6i8PwJRE8mifG/4bNz31hMWGdKKbDZSNFfWtnpIzcP7GlfQW1kIO9ITLSzLzK4mXfgglARn8dLypTFa0JMmzyyO4VJ9ooTc6PJl3JE1a8/Tgob1UFwgeMeUvvsaAKx9wuNSGDN7GhXmHbrMPky8Al2aUyEA+PxPeiQvEQR/Tiu2ocuqRIsBr5Cr4d3gmX5SE1qZIvm3Rdx+FTrJyyoFCcIW50X+xCq4VOWRR1z9LoQ7al0V09jR3N4liIA/fgSnm+ONlfI0d7sp79hksUCldr71EAue4Gi4ZBnEFMULjC80bdxO/Vbrv1/7hZ4Bu4tl5ELWcm1Dx6XkCa0K//+a4JrNSg+P8DSE2rPjndqBSPoy6vTCyHaPsa3wOXxEZoi9ezxm95I8Bzt1sqtal/8CzkZORI/RfnU7PEJ/Uhc1+D5ABvUI5M6pN6Fm87JUHcN8gp8pwCoStCvRLzeK0uYzkBS+S2kSVUj7cbJXdPsuDJ1YVBUZKjj56r0fZlGJBX3AoSWmbetrNLvZplEHze/TIoJ9YJuBk7RhYO6FsqD0/XYm6Wv9pO8H08EvJgJQS0JDjlpOj0zecEXDbz631qlKceK2G9qwbwssfLbq2+ooXVklVWs=
